@startuml diagrammaSVD

class Matrix{
    + int m
    + int n
    + int ld
    + double* matrix
    {static} + Matrix* randomMatrix (m,n,ld)

}

abstract class SvdEngine{
    
    {abstract} # init(Matrix*)
    {abstract} # Matrix*[ ] getOutputMatrices( )
    {abstract} # work( )
    {static} + SvdEngine factory (SvdEngineType)
}

enum SvdEngineType{
        CUSOLVERDNDGESVD
        MKL
        MAGMA
}

class CuSolverDnDgeSvdEngine{
    - copyToDevice( )
    - copyFromDevice( )
    # work( )
}

class TimeElapsed{
    + float getInitTime()
    + float getWorkingTime()
    + float getFinalizeTime()
    + float getTotalTime()
}

note bottom: Time in milliseconds

class SvdContainer{
    + SvdContainer(SvdEngine*)
    + setMatrix(Matrix*)
    + Matrix*[ ] getOutputMatrices( )
    + TimeElapsed* getTimeElapsed( )
}

SvdContainer ..>  Matrix : use
SvdContainer --> "1" SvdEngine
TimeElapsed "1" <- SvdContainer
SvdEngine -> "*" Matrix
SvdEngine <|-- CuSolverDnDgeSvdEngine

hide SvdEngine fields
hide TimeElapsed fields
hide SvdContainer fields
hide CuSolverDnDgeSvdEngine fields
hide SvdEngineType methods

@enduml