@startuml DenoisingDiagram

package denoisingLib{

    enum DenoiserType{
            CUDA_K_GESVD
            CUDA_K_GESVDJ
            CUDA_K_GESVDA
    }

    abstract class Denoiser{
        - String inputFile
        - String outputFile
        - CImg<float>* inputImage
        # int patchWidthDim
        # int patchHeightDim
        # int slidingWidth
        # int slidingHeight
        # int atoms
        # int iter
        # int ompIter
        # int sigma
        # bool speckle
        # String refImage
        # host_vector<double>* psnr

        {abstract} # bool loadImage()
        {abstract} # bool saveImage()
        {abstract} # bool internalDenoising()
        {abstract} + signed char denoising()
        + TimeElapsed* getTimeElapsed()
        + host_vector<double>* getPsnr()
        {static} + Denoiser* factory (DenoiserType, String, String)
    }

    note top: denoising = 0 --> SUCCESS\n = - i --> FAILED during i-th phase 

    class CudaKSvdDenoiser{

        - buildSvdContainer()
        - createPatches(bool)
        - initDictionary()
        - updateDictionary()
        - createImage(bool)
        - createImageFromSubImages()
        - kSvd()
        
        - int blocks
        - device_vector<int>* relevantDataIndices
        - device_vector<int>* relevantDataIndicesCounter
        # bool loadImage()
        # bool saveImage()
        # bool internalDenoising()
        + signed char denoising()
    }

    class BatchDenoiser{
        + host_vector<TimeElapsed*> getTimeElapsed() 
        + host_vector<host_vector<double>*> getPsnr()
        + host_vector<signed char> seqBatchDenoising()
        {static} + BatchDenoiser* factory (DenoiserType type, String)
    }

    note top: j-th batchDenoising = same as denoising()\nfirst TimeElapsed = sum single exec time 


    CudaKSvdDenoiser -|> Denoiser : extends
    DenoiserType "1"<- CudaKSvdDenoiser
    BatchDenoiser --> "*" Denoiser
    hide CudaKSvdDenoiser fields
    hide BatchDenoiser fields
    hide DenoiserType methods
}

package utilityLib{
    class Matrix
    class TimeElapsed
    

    hide Matrix fields
    hide Matrix methods

    hide TimeElapsed fields
    hide TimeElapsed methods

}

package matUtilityLib{
    abstract class MatrixOps
    hide MatrixOps fields
    hide MatrixOps methods
}

package SvdLib{
    class SvdContainer

    hide SvdContainer fields
    hide SvdContainer methods
}

BatchDenoiser ---> "*" TimeElapsed
Denoiser ---> "*" TimeElapsed
Denoiser ---> "*" Matrix
CudaKSvdDenoiser ---> "*" MatrixOps
CudaKSvdDenoiser ---> "*" SvdContainer

@enduml