@startuml MatUtilityDiagram

package matutilityLib{

    enum MatrixOpsType{
            CUBLAS_MULT
            CUBLAS_ADD
            CUBLAS_OMP
    }

    abstract class MatrixOps{

        # float alfa
        # float beta

        {abstract} # init()
        {abstract} # finalize()
        {abstract} + work(Matrix* a , Matrix* b)
        {abstract} + TimeElapsed* getTimeElapsed()
        + setCoff(float, float)
        {static} + MatrixMult* factory(MatrixOpsType)
    }

    class CuBlasMatrixMult{

        - cublasHandle_t handle
        - cublasOperation_t op1
        - cublasOperation_t op2
        - device_vector<float>* cVector

        # init()
        # finalize()
        + work(Matrix* a , Matrix* b)
        + setOps(cublasOperation_t, cublasOperation_t) 
    }

    class CuBlasMatrixAdd{

        - cublasHandle_t handle
        - cublasOperation_t op1
        - cublasOperation_t op2
        - device_vector<float>* cVector

        # init()
        # finalize()
        + work(Matrix* a , Matrix* b)
        + setOps(cublasOperation_t op1, cublasOperation_t op2)
    }

    class CuBlasMatrixOmp{
        - int maxIters
        - float epsilon
        - cublasHandle_t handle
        - device_vector<float>* cVector

        # init()
        # finalize()
        + work(Matrix* a , Matrix* b)
        + setLimits(float epsilon, int maxIters)
    }
    MatrixOps -> "1" MatrixOpsType 
    CuBlasMatrixMult --|> MatrixOps : extends
    CuBlasMatrixAdd --|> MatrixOps : extends
    CuBlasMatrixOmp --|> MatrixOps : extends

    hide MatrixOpsType methods 
}

package baseUtilityLib{
    class Matrix
    class TimeElapsed

    hide Matrix fields
    hide Matrix methods

    hide TimeElapsed fields
    hide TimeElapsed methods
}

MatrixOps --> "*" Matrix
MatrixOps --> "1" TimeElapsed

@enduml