@startuml OverviewDiagram
start
partition Initialization {
    :Load Image from file;
    :Calculate noise std dev;
    :Divide image in patches;
    :Init Dictionary matrix (D) from noisy patches;
}

partition Denoising {
    while(iter < maxIter)
        :Calculate sparse coeffs matrix (S) by OMP;
        :Update Dictionary (D) and coeffs matrix;
        :iter++;
    endwhile
    :Recalculate sparse coeffs matrix by OMP;
}

partition BuildImageDenosied {
    :(Patches) Y = D X S;
    :Build reconstructed image from patches and average with alpha*noisy image; 
}

stop
@enduml