@startuml OverviewDiagram
start
partition Initialization {
    :Load Image from file;
    :Calculate noise variance;
    :Divide image into nPatches noisy-patches;
    :Init Dictionary matrix (D) picking nAtoms patches from noisy-patches;
}

partition Denoising {
    while(iter < maxIter)
        :Calculate sparseCode matrix (S) by OMP;
        :Update Dictionary (D);
        :iter++;
    endwhile
    :Recalculate sparseCode matrix (S) by OMP;
}

partition BuildImageDenosied {
    :Build de-noised patches from D X S;
    :Build reconstructed image from de-noised patches and average with original alpha *noisy image; 
}

stop
@enduml